### ISSUE TITLE
[BC Break] Twig 3.29.0 breaks compat with symfony/twig-bundle 5.4.48

### ISSUE THREAD

**Issue by althaus** [twigphp/Twig#4942]
Hi,

I'm currently babysitting a legacy project stuck on Symfon 5.4. I've just updated Twig to 3.29 and this broke the app due to the change introduced in https://github.com/twigphp/Twig/commit/c1fc112047bd2c8bf5c4f4d762e52e7f48ccc602:

~~~php
public function unwrap(Environment $env): Template
{
    if ($this->env !== $env) {
        throw new RuntimeError(\sprintf('A "%s" can only be used with the "%s" that created it.', self::class, Environment::class));
    }

    return $this->template;
}
~~~

This introduced a required paramater.

vs.

https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheWarmer.php#L56

~~~php
                if (\is_callable([$template, 'unwrap'])) {
                    $files[] = (new \ReflectionClass($template->unwrap()))->getFileName();
                }
~~~

This calls the internal `unwrap` without any parameter.

The stack trace:

~~~
In TemplateWrapper.php line 110:

  [ArgumentCountError]
  Too few arguments to function Twig\TemplateWrapper::unwrap(), 0 passed in /app/vendor/symfony/twig-bundle/CacheWarmer/TemplateCacheWarmer.php on line 56 and exactly 1 expected


Exception trace:
  at /app/vendor/twig/twig/src/TemplateWrapper.php:110
 Twig\TemplateWrapper->unwrap() at /app/vendor/symfony/twig-bundle/CacheWarmer/TemplateCacheWarmer.php:56
 Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp() at /app/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:99
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /app/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:250
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmupOptionals() at /app/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:149
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /app/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /app/bin/console:38

cache:clear [--no-warmup] [--no-optional-warmers]
~~~

Cheers
Matthias

**Comment by fabpot** [comment]
Fixed in https://github.com/twigphp/Twig/pull/4936

**Comment by althaus** [comment]
Oh... sorry for the dupe then. Somehow missed that it's already fixed in master. My bad.
