### ISSUE TITLE
default filter does not work with objects that do not implement __toString()

### ISSUE THREAD

**Issue by eschultz-magix** [twigphp/Twig#2439]
I have reported the issue here https://github.com/sonata-project/SonataAdminBundle/issues/4446 but I think Twig has a BC break since version 1.33.0.

Example:

```php
class Foo {
  protected $bar;
}
```

Passing an instance of ```Foo``` class as ```foo``` variable to a twig template that uses the default filter will fail:

```twig
foo|default(null)
```

```
Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Method Foo::__toString() must return a string value")."
```

Having a look at the code introduced with https://github.com/twigphp/Twig/commit/f5193e92c50c89f19121771ca800aad55b97aff7 reveals the issue:

```
function _twig_default_filter($value, $default = '')
{
    if (twig_test_empty($value)) {
        return $default;
    }

    return $value;
}

function twig_test_empty($value)
{
    if ($value instanceof Countable) {
        return 0 == count($value);
    }

    if (method_exists($value, '__toString')) {
        return '' === (string) $value;
    }

    return '' === $value || false === $value || null === $value || array() === $value;
}
```

For every object that does not implement ```__toString()``` the ```'' === $value``` check will cast the object to string.

**Comment by stof** [comment]
``'' === $value`` will never cast, as it is a strict comparison (unless you compiled a custom version of PHP with a modified source code).

I rather think that your casting is triggered above by the code code added for objects implementing `__toString`, and that you have an object with a broken implementation.

**Comment by eschultz-magix** [comment]
@stof Thanks for the fast explanation. True that. My class is broken as it inherits from another class that returns ```NULL``` in ```__toString()```. I didn't check the inheritance, sorry.
