### ISSUE TITLE
Too few arguments to function Twig\TemplateWrapper::unwrap()

### ISSUE THREAD

**Issue by loicfontaine-creapluriel** [twigphp/Twig#4935]
Hello, we are working on a **Symfony 5.4** project and got a **CRITICAL** with the last version of twig (3.29.0)

```
Too few arguments to function Twig\TemplateWrapper::unwrap(), 0 passed in /xxx/vendor/symfony/twig bundle/CacheWarmer/TemplateCacheWarmer.php on line 56 and exactly 1 expected
```

Thank you for your work, have a nice day !

**Comment by mb-kh** [comment]
Same happened to me. It seems that twig 3.29.0 broke compatibility with twig-bundle 5.4.45.
Twig 3.28.0 works fine.

**Comment by loicfontaine-creapluriel** [comment]
> Same happened to me. It seems like that twig 3.29.0 broke compatibility with twig-bundle 5.4.45. Twig 3.28.0 works fine.

Indeed we are forced to lock the version to 3.28.0

**Comment by stof** [comment]
@fabpot this is caused by https://github.com/twigphp/Twig/pull/4910 changing the signature of the internal method.
The Symfony refactoring migrating away from using the Twig internal APIs (not covered by BC in Twig) was applied only in Symfony 6.4+.

**Comment by derrabus** [comment]
see #4936

**Comment by Asmitta-01** [comment]
I have the same issue on Symfony 8.0 and Symfony 8.1.
Locking the version to `3.28.*` is a workaround but I can't use [ux-toolkit 3.5](https://github.com/symfony/ux-toolkit/releases/tag/v3.5.1) then.

**Comment by stof** [comment]
@Asmitta-01 Symfony 8.1.7 does not use this internal Twig API anymore when using Twig 3.29+, so it is not affected.

**Comment by Asmitta-01** [comment]
@stof  Here is my composer.json(https://github.com/twigphp/Twig/issues/4944)

Did i missed something ? I can't render forms and can't revert too since i want to user ux-toolkit 3.5.1.
